const dynamicContent = {
    "ios": {
        "accent": "#F03457",
        "rgb": "240, 52, 87",
        "modules": [
            {
                "title": "Monopoly API & Data Integration Guide",
                "summary": "This document outlines the networking layer and data models for the Monopoly module.",
                "techDocs": "\n\n### Networking Architecture\nThe Monopoly module uses `RequestCreator` for building requests and `gAPIRequestManager` for execution, following the app's standard API pattern.\n\n### Base Request Creator\nMost requests are initiated through the `RequestCreator` class.\n\n### API Endpoints\n| Feature | Method | Request Creator Function | Purpose |\n| :--- | :--- | :--- | :--- |\n| **Dashboard** | GET | `createRequestForGetMonopolyTaskList` | Fetches tasks, dice count, and banner. |\n| **T&C** | POST | `createRequestForAcceptMonopolyTC` | Accepts game-specific terms. |\n| **Winner** | POST | `createRequestForFetchingMonopolyWinner` | Finalizes dice roll outcome. |\n| **Redeem** | POST | `createRequestForGetMonopolyRedeem` | Redeems an instant prize. |\n| **History** | GET | `createRequestForGetMonopolyHistory` | Fetches stickers and prize history. |\n| **Grand Gift** | GET | `createRequestForGetMonopolyGrandGift` | Initiates grand prize reveal flow. |\n| **Rules** | GET | `createRequestForGetMonopolyGameRules` | Fetches game mechanics & rules. |\n\n### Data Models (SwiftyJSON)\nThe module relies on the following key model hierarchies:\n\n### 1. Dashboard Model (`SMMonopolyDashboardBase`)\n- `data`: Contains `tasksList`, `availableRollDies`, `banner`, and `termsConditionLink`.\n- `isTermConditionAccepted`: Boolean flag for T&C visibility.\n- `isMonopolyEnabled`: Boolean to check if the event is active.\n\n### 2. Rewards Model (`CMMonoPRewardsDetailsBase`)\n- `type`: Outcome type (`INSTANT`, `GRAND`, `PRIZZLE`, `BETTER_LUCK_NEXT_TIME`).\n- `rollDies`: Remaining dice count after the roll.\n- `data`: Reward-specific details (image, name, etc.).\n\n### 3. History Model (`SMMonopolyHistoryBase`)\n- `grandPrizeList`: List of stickers for the puzzle.\n- `giftList`: List of instant prizes won.\n- `stickers`: Categories of stickers collected.\n\n### Error Handling & Status Codes\n- **200 OK**: Request successful.\n- **400 Bad Request**: Often returned when `availableRollDies` is 0 but a roll is attempted.\n- **Other Errors**: Standard network errors are caught and displayed via `CommonFunctions.showToastWithMessage`.\n\n### State Management (`ViewStatus`)\nEach ViewModel implements a `ViewStatus` enum to manage UI states:\n- `.idle`: Initial state.\n- `.loading`: API call in progress.\n- `.loaded`: Data successfully received.\n- `.empty`: Successful call but no data found.\n- `.failed(String)`: Error occurred with a message.",
                "code": "",
                "lang": "javascript",
                "id": "api_integration",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Analytics & Event Tracking",
                "summary": "This document specifies the events and properties tracked for MoEngage and CleverTap in the Monopoly module.",
                "techDocs": "\n\n### Tracking Managers\nThe module uses two primary event tracking managers:\n- **`MoEngageManager`**: For engagement events.\n- **`CleverTapManager`**: For event-based properties and behavioral tracking.\n\n### MoEngage Events\n| Event Key | Trigger Context | JSON Metadata (Properties) |\n| :--- | :--- | :--- |\n| `.monopoly_dashboard` | Dashboard screen loaded. | `no_of_roll_dices` |\n| `.roll_dice` | Valid dice roll initiated. | `dice_left` |\n| `.reveal_prize` | User reveals a prize (Grand/Instant). | `reveal_prize` (Outcome Type) |\n\n### CleverTap Events\n| Event Key | Trigger Context | JSON Metadata (Properties) |\n| :--- | :--- | :--- |\n| `visitedGame` | Dashboard screen loaded. | `no_of_roll_dices` |\n| `monopolyTermsAccepted` | T&C bottom sheet accepted. | - |\n| `monopolyGiftClaimed` | Instant prize redeemed. | - |\n| `clickedTask` | Task card tapped. | `task_name` |\n| `monopolyDiceRolled` | Valid dice roll initiated. | `dice_left` |\n| `monopolyHistoryViewed` | History (Win Big) screen loaded. | - |\n| `monopolyTabSwitched` | Switched between Stickers and Prizes. | `tab_name` |\n| `monopolyRulesViewed` | Game rules screen loaded. | - |\n\n### User-Level Properties (Context)\n- **`availableRollDies`**: Current dice count is often passed as a numeric property.\n- **`isTermConditionAccepted`**: State is often mirrored in user profiles for segmentation.\n\n### Best Practices\n- **Localization**: Properties should use English keys for consistency in analytical reports.\n- **Timing**: Track events AFTER the UI state transitions to ensure the data persists if the app backgrounded.",
                "code": "MoEngageManager.trackEvent(key: .roll_dice, \n                           json: [\"dice_left\": self.rewardsDetailsBase.rollDies])\n\nCleverTapManager.shared.track(CleverTapManager.Event.monopolyDiceRolled, \n                              props: [\"dice_left\": self.rewardsDetailsBase.rollDies])\n\n",
                "lang": "swift",
                "id": "analytics_tracking",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Architecture Overview",
                "summary": "The **Monopoly** module is built using a clean, modern architecture that bridges new SwiftUI views with existing UIKit infrastructure.",
                "techDocs": "\n\n### Architecture Pattern\n### MVVM (Model-View-ViewModel)\n- Each screen consists of:\n  - **View**: SwiftUI implementation for layout and visual logic.\n  - **ViewModel**: An `ObservableObject` that manages the state, business logic, and API calls.\n  - **Model**: SwiftyJSON-powered models for API data parsing.\n\n### Data Flow\n1. **View** triggers an action (e.g., dice roll).\n2. **ViewModel** calls the backend via `RequestCreator` and `gAPIRequestManager`.\n3. **API Success** updates `@Published` properties in the ViewModel.\n4. **SwiftUI View** automatically re-renders based on the state changes.\n\n### Integration & Tools\n- **Networking**: Uses `RequestCreator` for constructing API requests and `gAPIRequestManager` for execution.\n- **Analytics**: Both `MoEngageManager` and `CleverTapManager` are used for tracking game-related events.\n- **Navigation**: Managed via a `navigationCoordinator` to ensure seamless transitions between UIKit and SwiftUI environments.\n- **Localization**: Leverages `.monopolyLocalised` extensions for multi-language support.\n\n### Key Service Managers\n- **MoEngageManager**: Handles push notifications and event tracking for engagement.\n- **CleverTapManager**: Tracks user behavior and game events.\n- **CommonFunctions**: Utilities for activity loaders, toasts, and more.",
                "code": "",
                "lang": "javascript",
                "id": "architecture",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Localization & Multi-language Support",
                "summary": "The Monopoly module is designed to support multiple regions and languages using a combination of local extensions and backend-driven content.",
                "techDocs": "\n\n### Localization Mechanism\nStatic UI strings in the Monopoly module are localized via a custom extension:\n- **Usage**: `\"string\".monopolyLocalised`\n- **Supported Languages**: English (default), Vietnamese, and others configured in the app's overall localization system.\n\n### Dynamic Content Localization\nSince most game-related descriptions (task names, rewards) are fetched from the API, we use a custom JSON structure to manage translations:\n\n### 1. Model Support (`SMMonopolyTasksList`, `SMMonopolyGameRulesData`)\nModels contain language keys (`en`, `vi`, etc.) for each text field.\n\n### 2. Implementation in ViewModel\n```swift\nself.monopolyGameRules = self.monopolyTaskList.gameTermsCondition.map { item in\n    let json = JSON([\n        \"icon\": item.icon,\n        \"keyName\": [\"en\": item.keyName.en, \"vi\": item.keyName.vi],\n        \"valueName\": [\"en\": item.valueName.en, \"vi\": item.valueName.vi]\n    ])\n    return SMMonopolyGameRulesData(fromJson: json)\n}\n```\n\n### Key Localized Strings\n| English (en) | Description |\n| :--- | :--- |\n| **\"Roll & Win\"** | Dashboard main title. |\n| **\"Remaining Dice Rolls\"** | Count of rolls available to the user. |\n| **\"Shake your phone to roll dice\"** | Gameplay instruction. |\n| **\"My Gifts\"** | Navigation to history. |\n| **\"Win Big\"** | History screen title. |\n| **\"How you can Win?\"** | Step-by-step instructions. |\n\n### Adding New Localized Strings\n1. **Add Key**: Define a new key in the app's `Monopoly` localization dictionary.\n2. **Translate**: Provide translations for `en` and `vi`.\n3. **Use in View**: Call `.monopolyLocalised` on the string key inside the SwiftUI view.\n\n### Localization in Navigation\nThe `AJNavigationViewUI` takes localized titles but handles back buttons and layout based on the app's global RTL/LTR setting.\n\n### Best Practices\n- **Never Hardcode**: Avoid using plain strings; always wrap them in `.monopolyLocalised`.\n- **Backend Sync**: Ensure the backend sends the correct language key based on the user's selected language in the app header/profile.",
                "code": "",
                "lang": "javascript",
                "id": "localization",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Module Overview",
                "summary": "The **Monopoly** module is a gamified feature within the Livwell iOS app that encourages user engagement through tasks, dice rolls, and rewards. It follows a traditional Monopoly board game theme, where users earn \"Roll Dice\" by completing various health and wellness tasks.",
                "techDocs": "\n\n### Key Features\n- **Gamified Tasks**: Integration with daily wellness tasks (Steps, Water intake, Sleep, etc.) to earn dice rolls.\n- **Interactive Gameplay**: A virtual board where users roll dice to move through different spaces and claim rewards.\n- **Reward System**: Multiple reward types, including instant prizes and a grand prize reveal.\n- **History & Progress**: Detailed tracking of earned rewards and game progress.\n- **Terms & Rules**: Clear communication of game mechanics and legal disclosures.\n\n### User Flow\n1. **Dashboard Entry**: The user enters from the main app dashboard.\n2. **Accept Terms**: If it's their first time, they must agree to the Monopoly-specific terms and conditions.\n3. **Earn Dice**: Users complete tasks to earn more rolls.\n4. **Gameplay**: Users roll dice to move across the board.\n5. **Claim Prizes**: Landing on specific spaces triggers rewards or prize reveals.\n6. **History**: Users can view their reward history at any time.\n\n### Technical Foundation\n- **SwiftUI & UIKit Interop**: Uses modern SwiftUI for most views, integrated with existing UIKit navigation.\n- **MVVM Architecture**: Clean separation of concerns with dedicated ViewModels for each screen.\n- **Real-time Synchronization**: API calls ensure game state (dice rolls, task completion) is always up-to-date with the backend.\n- **Analytics**: Comprehensive tracking of game events via MoEngage and CleverTap.",
                "code": "",
                "lang": "javascript",
                "id": "overview",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Dice Roll Gameplay (Shake Dice)",
                "summary": "The **Shake Dice** screen is where the actual gameplay happens. It uses device sensors to detect a \"shake\" motion, which then triggers the dice rolling animation and determines the outcome of the roll.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyDiceRoll.swift`\n- **ViewModel File**: `DiceRollViewModel.swift`\n- **Feature Name**: Shake Dice (Gameplay)\n\n### Key Components\n### 1. Navigation & Dice Count\n- Shows current **Remaining Dice Rolls**.\n- Interactive pop gesture is disabled while dice are animating.\n\n### 2. Dice Area\n- Displays a tilting \"FrameDice\" icon when idle.\n- Switches to high-frame-rate animation (`DiceFrameAnimation`) when the user shakes their phone.\n\n### 3. Messaging\n- Instruction text: \"Shake your phone to roll dice\".\n- Hidden during animation to avoid clutter.\n\n### Business Logic & State\n- **Shake Detection**: Uses `CMMotionManager` to monitor device acceleration. Returns magnitude > 2 for a valid shake.\n- **Animation Sequence**: \n  - Play `diceRoll` tone. \n  - Trigger short vibration.\n  - Run frame animation for the dice.\n  - Call winning determination API on completion.\n- **Navigation Callbacks**: Passes success results back to navigation to show \"Instant\" or \"Grand Prize\" rewards.\n\n### API Integration\n| Action | API Request | Purpose |\n| :--- | :--- | :--- |\n| Determine Result | `createRequestForFetchingMonopolyWinner` | Finalizes the result of the dice roll (Instant/Grand Prize/Next Time). |\n\n### Navigation\n- **Into the Screen**: From the **Monopoly Dashboard** by tapping \"Roll Dice\".\n- **Out of the Screen**: \n  - To **Instant Prize Reveal**: Landing on an instant prize.\n  - To **Grand Prize Reveal**: Landing on a sticker or grand prize.\n  - To **Better Luck Next Time**: Shown via a custom `DiceRollAlertView`.\n  - Manual Close: Tapping the back button (only allowed when not animating).\n\n### Animation Technical Detail\n- Uses a sequence of 129 images (`frame_000` to `frame_128`) played at 30 fps using a `Timer` to create a smooth 3D-like dice roll experience.",
                "code": "",
                "lang": "javascript",
                "id": "screen_dicerollgameplay",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Game Rules & Terms",
                "summary": "The **Game Rules** and **Terms & Conditions** screens ensure that users understand how to play the Monopoly game and agree to the legal requirements of participation.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyGameRulesView.swift`, `MonopolyTCView.swift`\n- **ViewModel File**: `MonopolyGameRulesViewModel.swift`\n- **Feature Name**: Game Rules / T&C\n\n### Key Components\n### 1. Game Rules List\n- Displays a vertical list of rules using `GameRuleCard`.\n- Each card includes an icon, a **Key Name** (Title), and a **Value Name** (Description).\n- Rules are fetched dynamically from the backend to ensure they are always up-to-date.\n\n### 2. Terms & Conditions (T&C) Bottom Sheet\n- A modal view (`MonopolyTCView`) that appears on the **Monopoly Dashboard** for first-time users.\n- Includes a summary of rules and an \"Accept\" button.\n- Provides a link to the full Terms & Conditions document via a Safari web view.\n\n### Business Logic & State\n- **Dynamic Content**: Both screens use `@Published` properties derived from JSON models (`SMMonopolyGameRulesData`).\n- **T&C Enforcement**: The game is locked behind the T&C acceptance logic in `MonopolyHomeUIViewModel`.\n- **Analytics**: Both screens track viewing events (`monopolyRulesViewed`, `monopolyTermsAccepted`).\n\n### API Integration\n| Action | API Request | Purpose |\n| :--- | :--- | :--- |\n| Fetch Rules | `createRequestForGetMonopolyGameRules` | Loads the list of rules and regulations. |\n| Accept T&C | `createRequestForAcceptMonopolyTC` | Registers the user's acceptance and unlocks the game. |\n\n### Navigation\n- **Into Game Rules**: \n  - From **Monopoly Dashboard** via \"Game Rules\" button.\n  - From **Rewards History** via the \"?\" icon.\n- **Out of Game Rules**: \n  - Back to previous screen via the standard navigation back button.\n- **T&C Link**: Opens the external terms URL in a `SFSafariViewController`.",
                "code": "",
                "lang": "javascript",
                "id": "screen_gamerules_tc",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Rewards History (Win Big)",
                "summary": "The **Rewards History** screen (titled \"Win Big\") allows users to track their progress, view collected stickers, and manage their earned prizes.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyHistoryViewUi.swift`\n- **ViewModel File**: `MonopolyHistoryViewModel.swift`\n- **Feature Name**: Win Big (History)\n\n### Key Components\n### 1. Tab Segmented Control\n- **Stickers**: Displays the puzzle-like sticker collection progress.\n- **Prizes**: Shows both grand prizes won and instant gifts collected.\n\n### 2. Sticker Collection Grid\n- Uses `MonopolyStickerHistoryCard` to display stickers in a grid.\n- Each sticker shows its status (Locked/Revealed) and theme-specific colors.\n- Tapping a sticker can reveal more details or the collection status.\n\n### 3. Grand Prizes & Gifts\n- **Grand Prizes**: A horizontal scroll of major rewards.\n- **Gifts**: A grid of instant prizes (vouchers, points, etc.).\n- **View All**: If the user has more than 6 gifts, a \"View all\" button navigates to `AllInstantGiftUI`.\n\n### 4. Gift Unlock Bottom Sheet\n- Tapping a prize opens a `MonopolyGiftUnlockBS` to show collection info or voucher codes.\n\n### Business Logic & State\n- **Segment Handling**: Managed via `MonopolySegment` enum.\n- **Lock/Unlock Visuals**: Uses opacity (0.5 for locked, 1.0 for revealed/unblocked) to visually distinguish state.\n- **Refresh Mechanism**: Standard loading, empty, and error state handling with manual refresh support.\n\n### API Integration\n| Action | API Request | Purpose |\n| :--- | :--- | :--- |\n| Fetch History | `createRequestForMonopolyHistory` | Loads stickers, grand prizes, and gift history. |\n\n### Navigation\n- **Into the Screen**: \n  - From **Monopoly Dashboard** via \"My Gifts\".\n  - Automatically after certain rewards are won.\n- **Out of the Screen**: \n  - To **Reward Details**: Tapping a gift card opens `AppRouter.openPurchasedRewardDetails`.\n  - To **View All Gifts**: Tapping \"View all\" opens `AllInstantGiftUI`.\n  - To **Game Rules**: Tapping \"Game Rules\" in the navigation bar.",
                "code": "",
                "lang": "javascript",
                "id": "screen_history_rewards",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Monopoly Dashboard (Roll & Win)",
                "summary": "The **Monopoly Dashboard** is the main screen of the module, where users can view their progress, earn dice through tasks, and initiate gameplay.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyHomeView.swift`\n- **ViewModel File**: `MonopolyHomeUIViewModel.swift`\n- **Feature Name**: Roll & Win (Monopoly)\n\n### Key Components\n### 1. Hero Banner\n- Displays the main event banner.\n- Shows total **Available Roll Dice**.\n- Provides a \"Roll Dice\" button that navigates to the **Shake Dice** screen.\n\n### 2. Task Grid\n- Displays available tasks in a multi-column horizontal scroll.\n- Tasks are categorized and linked to specific wellness activities (Steps, Water, Face Scan, etc.).\n- Each task card shows the task title and an icon.\n\n### 3. \"How to Win\" Section\n- Provides step-by-step instructions on how to participate.\n- Links to the **Game Rules** screen for detailed mechanics.\n\n### 4. Floating Gift Button\n- Appear when a user has a \"Grand Gift\" to reveal.\n- Shows a badge with the count of available grand prize reveals.\n- Triggers `callApiForGetMonopolyGrandGift()` when tapped.\n\n### Business Logic & State\n- **ViewStatus**: The screen handles multiple states (`loading`, `loaded`, `empty`, `failed`) to provide a robust user experience.\n- **Terms & Conditions**: On the first entry, the `MonopolyTCView` bottom sheet is automatically triggered if `isTermConditionAccepted` is false.\n- **Data Refresh**: Pull-to-refresh and manual refresh buttons (in empty/error states) trigger `callApiForMonopolyTaskList()`.\n\n### API Integration\n| Action | API Request | Purpose |\n| :--- | :--- | :--- |\n| Fetch Dashboard | `createRequestForGetMonopolyTaskList` | Loads tasks, dice count, banner, and grand prize info. |\n| Accept T&C | `createRequestForAcceptMonopolyTC` | Registers user's agreement to the game terms. |\n| Reveal Grand Gift | `createRequestForGetMonopolyGrandGift` | Initiates the grand prize reveal process. |\n\n### Navigation\n- **Into the Screen**: Usually from the main app dashboard.\n- **Out of the Screen**: \n  - To **Shake Dice**: Tapping the \"Roll Dice\" button.\n  - To **History**: Tapping the \"My Gifts\" button in the navigation bar.\n  - To **Game Rules**: Tapping the \"Game Rules\" button.\n  - To **Task Description**: Tapping any task card.",
                "code": "",
                "lang": "javascript",
                "id": "screen_monopolydashboard",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Prize Reveal",
                "summary": "The **Prize Reveal** screen is the rewarding climax of the Monopoly experience. It can display an instant reward, a collected sticker (for the grand prize puzzle), or a \"Better Luck Next Time\" message.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyGrandPriceDisplayView.swift`\n- **ViewModel File**: `MonopolyGrandPriceDisplayViewModel.swift`\n- **Feature Name**: Prize Reveal\n\n### Key Components\n### 1. Interactive Gift Box\n- Initially shows a closed, \"jiggling\" gift box (`bt_grand_prize_icon`).\n- Users must tap to trigger the \"Open\" animation.\n- Uses a `JelloEffect` view modifier for a playful, bouncy physical feel.\n\n### 2. Reward Display\n- **Grand Prize Sticker**: Shows the specific sticker image.\n- **Instant Gift**: Displays the reward card (voucher, points, etc.).\n- **Better Luck Next Time**: Shows a simplified card for non-winning rolls.\n\n### 3. Visual Effects\n- **Confetti**: A Lottie animation (`confity_lottie`) plays when a significant prize is revealed.\n- **Sunburst Background**: A dynamic background that enhances the sense of excitement.\n\n### 4. Post-Reveal Actions\n- **Re-Roll Dice**: Visible if the user has remaining rolls, allowing them to jump straight back into gameplay.\n- **View All Stickers**: Navigates the user to their sticker collection/history.\n\n### Business Logic & State\n- **Two-Tap Flow**: First tap opens the box; second tap (or tapping action buttons) proceeds with the next step.\n- **Animation Orchestration**: Uses a series of state changes (`showClosedBox` -> `showOpenBox` -> `showGiftCard` -> `showButtons`) to create a satisfying timed sequence.\n\n### API Integration\n*Note: This screen primarily displays results fetched after a dice roll or during a grand prize reveal.*\n\n### Navigation\n- **Into Prize Reveal**: \n  - Automatically after a winning **Dice Roll**.\n  - From the **Monopoly Dashboard** via the floating gift button.\n- **Out of Prize Reveal**: \n  - To **Shake Dice**: Tapping \"Re-Roll Dice\".\n  - To **Rewards History**: Tapping \"View All Stickers\".\n  - Dismiss: Controlled via the `onCompletion` callback to ensure the parent screen refresh.",
                "code": "",
                "lang": "javascript",
                "id": "screen_prizereveal",
                "category": "Monopolydocs"
            },
            {
                "title": "Screen: Task Description",
                "summary": "The **Task Description** screen is a detailed bottom-sheet view that provides the user with specific information about a selected task, including the requirements to complete it and the rewards associated with it.",
                "techDocs": "\n\n### Metadata\n- **View File**: `MonopolyTaskDescriptionView.swift`\n- **Parent View**: `MonopolyHomeView.swift`\n- **Feature Name**: Task Details\n\n### Key Components\n### 1. Task Header\n- Displays the large **Task Icon** and **Title**.\n- Styled with a dark background to match the Monopoly theme.\n\n### 2. Information Blocks\n- **\"What to do\"**: Explains the steps the user needs to take to complete the task.\n- **\"What you get?\"**: Details the rewards (e.g., number of dice rolls) earned upon completion.\n- Uses `TaskInfoBlock` for a consistent, card-based layout.\n\n### 3. Action Button\n- If the task is enabled, a large **\"Join Now\"** or **\"Refer a Friend\"** button is displayed at the bottom.\n- Triggers the corresponding app action (e.g., navigating to the referral screen).\n\n### Business Logic & State\n- **Drag-to-Dismiss**: Implements a standard iOS bottom-sheet gesture using `DragGesture` and `dragOffset`.\n- **Dynamic Content**: Data is populated from the `SMMonopolyTasksList` model passed from the dashboard.\n- **Conditional Rendering**: The action button only appears if `task.isEnabled` is true.\n\n### API Integration\n*Note: This screen primarily displays data already fetched by the Monopoly Dashboard API.*\n\n### Navigation\n- **Into Task Description**: Tap any task card on the **Monopoly Dashboard**.\n- **Out of Task Description**: \n  - Drag the sheet down.\n  - Tap the dimmed background area.\n  - Tap the action button (which also triggers the respective app feature).",
                "code": "",
                "lang": "javascript",
                "id": "screen_taskdescription",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly State Management & Architecture",
                "summary": "This document details the MVVM implementation and data persistence patterns within the Monopoly module.",
                "techDocs": "\n\n### Core ViewModel Architecture\nThe module uses `@StateObject` and `@ObservedObject` for a clean, modern data flow.\n\n### 1. `MonopolyHomeUIViewModel` (The Orchestrator)\n- **Role**: Manages the dashboard lifecycle, T&C acceptance, and task lists.\n- **Key State**:\n  - `status: ViewStatus`: Controls the overall screen UI (loading, loaded, empty, failed).\n  - `monopolyTaskList: SMMonopolyDashboard`: The primary data source.\n  - `showTCBottomSheet: Bool`: Triggers T&C visibility.\n- **Persistence**: Most state is derived from API calls; local state is cleared when the view is de-initialized.\n\n### 2. `DiceRollViewModel` (Gameplay)\n- **Role**: Manages the sensor-driven gameplay logic and outcomes.\n- **Key State**:\n  - `isAnimating: Bool`: Disables the back button and interaction during rolls.\n  - `remainingRolls: Int`: Tracks the user's available dice count.\n  - `prizeType: MonopolyGiftType?`: Stores the result of the current roll.\n\n### 3. `MonopolyHistoryViewModel` (Persistence Layer)\n- **Role**: Manages the sticker collection and prize history.\n- **Support**: Includes `loadMockData()` to facilitate testing with offline JSON.\n\n### Inter-Component Communication\nThe module communicates between screens using a mix of SwiftUI and UIKit:\n\n- **Navigation Coordinator**: Uses `navigationCoordinator.pushSwiftUIView` to navigate between views while passing ViewModels or models as dependencies.\n- **Callbacks**: Uses `onCompletion` closures to notify parent views when a task is completed (e.g., after a prize reveal).\n\n### Data Synchronization Pattern\n1. **Dashboard Fetch**: Initial data load.\n2. **Action Trigger**: User rolls dice or completes a task.\n3. **API Confirmation**: Backend updates the user's game state.\n4. **Local Update**: The ViewModel updates its `@Published` properties, which automatically re-renders the SwiftUI Views.\n\n### Observable Object Patterns\n- **`@StateObject`**: Used in main views (Home, History) to manage the primary ViewModel lifecycle.\n- **`@ObservedObject`**: Used in sub-components to ensure they stay in sync with the parent data.\n- **`@Environment(\\.presentationMode)`**: Used for dismissing views and handling back navigation.\n\n### Best Practices\n- **Single Source of Truth**: Always derive UI state from the API model where possible.\n- **Async Main Threading**: Use `DispatchQueue.mainQueueAsync` for all UI updates inside API callbacks.\n- **Memory Management**: Use `[weak self]` in all closures and API callbacks to prevent retain cycles.",
                "code": "",
                "lang": "javascript",
                "id": "state_management",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Testing & QA Guide",
                "summary": "This document provides a roadmap for testing the Monopoly module, covering primary user flows, edge cases, and simulation tools.",
                "techDocs": "\n\n### Testing Setup & Simulation\n### 1. Developer Testing Mode (`DiceRollViewModel.swift`)\nToggle `TESTING_MODE = true` in `DiceRollViewModel` to simulate winning results without needing a stable backend environment. This avoids using real dice counts.\n\n### 2. Simulator vs. Physical Device\n- **Physical Device**: Required for testing **Shake Motion Detection** (`CMMotionManager`).\n- **Simulator**: Implements a 2-second timeout fallback that automatically triggers `callWebserviceForMonopolyWinner()` to simulate a shake.\n\n### Manual Test Cases\n### 1. First-Time Entry & T&C\n- **Scenario**: User enters Monopoly for the first time.\n- **Expected**: `MonopolyTCView` bottom sheet is visible. Users cannot interact with the dashboard until \"Accept\" is tapped.\n- **Edge Case**: Tap the \"Exit\" or \"Cancel\" button; verify the user is redirected back to the app home.\n\n### 2. Earning Dice via Tasks\n- **Scenario**: User taps on a task from the grid.\n- **Expected**: `MonopolyTaskDescriptionView` opens, showing details.\n- **Action**: Tap the \"Join Now\" or \"Refer a Friend\" button; verify correct app navigation.\n\n### 3. Gameplay (Shake to Roll)\n- **Scenario**: User has 1+ dice and enters the Shake screen.\n- **Action**: Vertically shake the phone.\n- **Expected**: `diceRoll` sound plays, phone vibrates, frame animation runs.\n- **Edge Case**: Shake with 0 dice. Verify the \"No Roll Dice\" alert is shown.\n\n### 4. Prize Reveal Flow\n- **Scenario**: User lands on a prize.\n- **Action**: Tap the bouncing gift box.\n- **Expected**: `Sunburst` background appears, box opens, reward is shown.\n- **Action**: Tap \"Re-Roll Dice\". Verify seamless transition back to the Shake screen.\n\n### 5. History & Progress\n- **Scenario**: User navigates to \"My Gifts\".\n- **Action**: Switch between \"Stickers\" and \"Prizes\" tabs.\n- **Expected**: Correct lists are loaded. Locked stickers should be dimmed (50% opacity).\n\n### Edge Case Testing\n| Case | Expected Outcome |\n| :--- | :--- |\n| **No Internet** | Show an error state or toast message with a \"Try Again\" option. |\n| **0 Dice Rolls** | Disable the \"Roll Dice\" button on the dashboard or show an error toast. |\n| **App Killed During Animation** | Upon restart, the dice should be deducted, and the prize should be available in the \"History\" screen. |\n| **Fast Tapping** | Rapid tapping on buttons should be ignored using the `lastTapTime` throttle logic. |\n\n### Visual Quality Assurance (UI/UX)\n- Verify that the floating gift button is correctly badged with the count.\n- Ensure the `Sunburst` background doesn't clip on different screen sizes (iPhone 7 vs. iPhone 15 Pro).\n- Check that long task names don't break the card layouts.",
                "code": "",
                "lang": "javascript",
                "id": "testing_guide",
                "category": "Monopolydocs"
            },
            {
                "title": "Monopoly Theme & Visual Assets",
                "summary": "The Monopoly module uses a custom color palette and a specific set of visual assets to create a premium gamified experience.",
                "techDocs": "\n\n### Color Palette\nDefined in `Color` extensions, the Monopoly module uses a sophisticated dark theme with vibrant accents.\n\n| Color Name | Hex Code | Purpose |\n| :--- | :--- | :--- |\n| **`monopolyBg`** | `#201E1F` | Main screen background. |\n| **`monopolyPrimary`** | `#F03457` | Primary action buttons and highlights. |\n| **`monopolyCard`** | `#DA2128` (25% opacity) | Task and prize card backgrounds. |\n| **`monopolyDarkRed`** | `#DA2128` | Secondary accent and floating buttons. |\n| **`monopolyTextPrimary`** | `#FDFCFC` | Main body text and titles. |\n| **`monopolyTextSecondary`** | `#B1B1B2` | Subtitles and captions. |\n\n### Typography\nThe module uses the **Manrope** font family for a modern, accessible look.\n\n- **Main Titles**: `.manrope(.bold, size: 20)`\n- **Body Text**: `.manrope(.medium, size: 14)`\n- **Captions**: `.manrope(.regular, size: 12)`\n- **Button Labels**: `.manrope(.semiBold, size: 16)`\n\n### Core Image Assets\n- **`FrameDice`**: Static dice image for the idle state.\n- **`Dice`**: Large hero asset for the dashboard banner.\n- **`bt_grand_prize_icon`**: The bouncing prize box image.\n- **`bt_grand_prize_open_icon`**: The revealed prize box image.\n- **`giftVector`**: Navigation bar icon for \"My Gifts\".\n- **`gift2`**: Floating gift reveal button asset.\n- **`Sunburst`**: Background rays for the prize reveal screen.\n\n### Animations (Lottie & Frame-based)\n- **`confity_lottie`**: A Lottie JSON file played on successful prize reveals.\n- **Dice Animation**: A sequence of 129 images (`frame_000` to `frame_128`) played manually in `DiceFrameAnimation`.\n\n### UI Components & Design Language\n- **Glassmorphism**: Uses dynamic linear gradients and low-opacity fills to create a \"glass\" effect on cards.\n- **Shadows**: Deep shadows (`radius: 12`, `opacity: 0.25`) are used on rules and prize cards for depth.\n- **Micro-interactions**: Uses `JelloEffect` (bouncy box) and `rotationEffect` (tilting dice) to make the UI feel alive.",
                "code": "",
                "lang": "javascript",
                "id": "theme_assets",
                "category": "Monopolydocs"
            },
            {
                "title": "Habit Tracker Architecture",
                "summary": "- **Framework**: SwiftUI (primarily) with some UIKit integration where necessary.",
                "techDocs": "\n\n### Technical Stack\n- **Framework**: SwiftUI (primarily) with some UIKit integration where necessary.\n- **Pattern**: MVVM (Model-View-ViewModel).\n- **Network**: Integrated with `gAPIRequestManager` using `RequestCreator` for API calls.\n- **State Management**: Uses `@StateObject` and `@Published` in ViewModels for reactive UI updates.\n\n### Core Components\n### 1. View Layer\nThe views are built using SwiftUI, emphasizing a clean and responsive layout. They are modularized into components (e.g., `HabitCell`, `StreakCard`) to ensure reusability.\n- **Entry Points**: `HabitTrackingHomeDashboardViewUI` is the primary entry point.\n- **Navigation**: Uses `AJNavigationCoordinator` or standard SwiftUI navigation depending on the context.\n\n### 2. ViewModel Layer\nEach major screen has a corresponding ViewModel that inherits from `ObservableObject`.\n- **Responsibilities**: \n    - Managing local state (e.g., `addedHabitList`, `notesText`).\n    - Handling user interactions (e.g., `updateLogsStatus`, `updateDeleteSelection`).\n    - Orchestrating API calls via `RequestCreator`.\n    - Parsing JSON responses using `SwiftyJSON`.\n- **Key ViewModels**:\n    - `HabitTrackingHomeDashboardUIViewModel`: Manages the dashboard state and logs.\n    - `AddHabitsUIViewModel`: Manages the habit search and selection logic.\n    - `SetHabitReminderUIViewModel`: Manages reminder settings and scheduling.\n\n### 3. Model Layer\nModels represent the data structure of habits, dashboards, and API responses.\n- **Entities**: \n    - `SMHabit`: Represents a single habit item.\n    - `SMHabitDashboard`: Represents the overall dashboard state.\n    - `SMHabitsByDate`: Contains habits for a specific calendar day.\n    - `SMBaseHabitDashboard`: The root response model from the dashboard API.\n\n### Data Flow\n1. **Initial Load**: ViewModel calls `initialSetup()` to determine date ranges and then `callWebServiceForFetchingHabitDashboardList()`.\n2. **User Action**: User toggles a habit completion status.\n3. **Local Update**: ViewModel updates the `addedHabitList` and sets `isLogStatusChanged = true`.\n4. **Sync**: User taps \"Keep Moving Forward\" (Save), triggering `callWebServiceForLoggingHabitDashboardList()`.\n5. **UI Refresh**: On success, the ViewModel parses the new state and updates the `@Published` properties, causing the SwiftUI view to re-render.\n\n### API Integration\nThe module communicates with the backend through several key endpoints:\n- **Fetch Dashboard**: Retrieves the user's habits, streaks, and suggestions.\n- **Log Habits**: Synchronizes the completion status of habits for a specific day.\n- **Add Habits**: Adds new habits from the catalog to the user's active list.\n- **Delete Habits**: Removes habits from the user's active list.\n- **Reminders**: Updates notification preferences for habits.",
                "code": "",
                "lang": "javascript",
                "id": "architecture",
                "category": "Habittrackerdocs"
            },
            {
                "title": "Habit Tracker Module Overview",
                "summary": "The Habit Tracker module in the LivWell application is designed to help users build and maintain healthy habits. It allows users to select from a variety of suggested habits or search for specific ones, track their daily progress, view streaks, and set reminders to stay consistent.",
                "techDocs": "\n\n### Purpose\nThe Habit Tracker module in the LivWell application is designed to help users build and maintain healthy habits. It allows users to select from a variety of suggested habits or search for specific ones, track their daily progress, view streaks, and set reminders to stay consistent.\n\n### Key Features\n- **Daily Progress Tracking**: Users can log their habits as 'Completed' or 'Skipped' for each day.\n- **Streak Management**: Tracks consecutive days of habit completion to provide motivation through streaks.\n- **Habit Catalog**: A comprehensive list of habits categorized by focus areas (e.g., Physical, Mental, Lifestyle).\n- **Reminders**: Customizable notifications to prompt users to complete their habits.\n- **Notes**: Ability to add daily notes to track additional context or reflections on habit progress.\n- **Suggested Habits**: Personalized recommendations based on user goals or popular habits.\n\n### User Flow\n1. **Entry**: Users enter the Habit Tracker from the Home or Rewards dashboard.\n2. **Dashboard**: The main screen shows current streaks and habits for the selected date (defaulting to today).\n3. **Logging**: Users tap on a habit to toggle its completion status.\n4. **Adding Habits**: Users can tap \"Add Habits\" to browse the catalog and select new ones.\n5. **Managing Habits**: Users can delete habits, edit notes, or set reminders from the dashboard or habit details.\n6. **Streaks**: Users can view their streak history and details to understand their long-term progress.\n\n### Module Structure\nThe module is organized into several sub-views, each handling a specific part of the habit-tracking experience:\n- `01HabitTrackingHomeDashboardViewUI`: The central hub for daily tracking.\n- `02AddHabitsViews`: Interface for discovering and adding new habits.\n- `03SetHabitReminderViewUI`: Configuration for habit-specific reminders.\n- `04StreakDashboardUI` & `05StreakActivityDetailsUI`: Visualization of consistency and progress.\n- `04EditHabitNotesViewUI`: Detailed note-taking for daily reflections.",
                "code": "",
                "lang": "javascript",
                "id": "overview",
                "category": "Habittrackerdocs"
            },
            {
                "title": "Screen: Choose Habits (Add Habits)",
                "summary": "The Choose Habits screen allows users to discover new habits and add them to their daily tracking list. It provides categorized browsing and a global search feature to help users find habits that align with their health goals.",
                "techDocs": "\n\n### Purpose\nThe Choose Habits screen allows users to discover new habits and add them to their daily tracking list. It provides categorized browsing and a global search feature to help users find habits that align with their health goals.\n\n### Files\n- **Views**: \n    - `01ChooseHabitViewUI/HabitTrackingChooseHabitViewUI.swift`\n    - `02ChooseHabitSearchViewUI/HabitTrackingChooseHabitSearchViewUI.swift`\n- **ViewModel**: `ChooseHabitUIViewModel.swift`\n- **Strings**: `ChooseHabitViewUIStrings.swift`\n\n### UI Components\n- **Category Tabs**: A horizontal list of habit categories (e.g., Physical, Mental, Nutrition). Selecting a category filters the habit list.\n- **Habit Grid/List**: Displays habit cards with name, description, and an \"Add\" toggle.\n- **Search Bar**: Navigates to a dedicated search screen for finding habits by keyword.\n- **Active Habit Counter**: Informs the user how many habits are currently in their active list.\n- **Next/Save Button**: Confirms the selection of one or more habits and adds them to the user's dashboard.\n\n### Business Logic\n- **Category Filtering**: Selecting a category updates `filteredHabitList` with habits belonging specifically to that category.\n- **Selection State**: Users can select multiple habits across different categories. The ViewModel tracks these in its internal data structure.\n- **Search Logic**: Global search filters the entire `searchHabitList` based on the user's text input.\n- **Syncing New Habits**: Clicking \"Next\" calls the API to persist the newly selected habits. On success, it refreshes the dashboard ViewModel.\n\n### API Integration\n- `createRequestForFetchingHabitList`: Retrieves all available habit categories and their corresponding habits.\n- `createRequestForCreatingHabitList`: Sends the list of selected habit IDs to the server to be added to the user's profile.\n\n### Navigation\n- **Inbound**: From the Habit Dashboard via the \"Add Habits\" button.\n- **Outbound**:\n    - **Dashboard**: Returns to the main dashboard after successfully adding habits.\n    - **Reminders**: If new habits are added, the user may be prompted to set reminders.",
                "code": "",
                "lang": "javascript",
                "id": "screen_addhabits",
                "category": "Habittrackerdocs"
            },
            {
                "title": "Screen: Habit Tracking Dashboard",
                "summary": "The Habit Tracking Dashboard is the primary interface for users to monitor and log their daily habits. It provides a visual representation of current streaks, a date selector for past/future logs, and the list of habits to be completed for the selected day.",
                "techDocs": "\n\n### Purpose\nThe Habit Tracking Dashboard is the primary interface for users to monitor and log their daily habits. It provides a visual representation of current streaks, a date selector for past/future logs, and the list of habits to be completed for the selected day.\n\n### Files\n- **View**: `HabitTrackingHomeDashboardViewUI.swift`\n- **ViewModel**: `HabitTrackingHomeDashboardUIViewModel.swift`\n- **Strings**: `HabitTrackingHomeDashboardViewUIStrings.swift`\n\n### UI Components\n- **Streak Header**: Displays the current number of days the user has maintained their habits.\n- **Date Selector**: A horizontal scrollable list of dates (last 7 days by default) for selecting which day's habits to view/log.\n- **Habit List**: A list of `HabitCell` components showing the habit name, icon, and completion status.\n- **Notes Section**: Short snippet of notes for the current day with an \"Edit\" button.\n- **Action Buttons**:\n    - **Save (Keep Moving Forward)**: Visible when changes are made to the habit logs.\n    - **Delete Icon**: Enables selection mode to remove habits.\n    - **Add Habits Button**: Navigates to the habit discovery screen.\n- **Suggested Habits**: A horizontal list of recommended habits displayed when the user has few or no active habits.\n\n### Business Logic\n- **Date Selection**: Tapping a date updates `lastSelectedDate` and filters `addedHabitList` to show habits for that specific day.\n- **Logging**: Tapping a habit cycles its status between `completed`, `skipped`, and `notAttended`. Local changes are tracked via `isLogStatusChanged`.\n- **Note Management**: Displays the note for the selected date. Clicking \"Edit\" opens the `EditHabitNotesViewUI`.\n- **Deletion Mode**: Users can toggle a delete mode, select multiple habits, and confirm their removal via an API call.\n- **Syncing**: The \"Keep Moving Forward\" button triggers a bulk update of all habit statuses for the day to the server.\n\n### API Integration\n- `createRequestForFetchingHabitDashboardList`: Fetches all data for the dashboard (streaks, habits for the week, suggestions).\n- `createRequestForLoggingHabitDashboardList`: Sends the updated completion statuses and notes to the server.\n- `createRequestForDeletingHabitList`: Removes one or more selected habits from the user's list.\n\n### Navigation\n- **Inbound**: Usually from the Rewards Dashboard or Home screen.\n- **Outbound**:\n    - `AddHabitsViews`: Via the \"Add Habits\" button or suggested habit cards.\n    - `EditHabitNotesViewUI`: Via the \"Edit/Write\" notes button.\n    - `StreakDashboardUI`: By tapping on the streak header.\n    - `SetHabitReminderViewUI`: Accessed via habit settings or the reminder icon.",
                "code": "",
                "lang": "javascript",
                "id": "screen_habitdashboard",
                "category": "Habittrackerdocs"
            },
            {
                "title": "Screen: Reminders & Notes",
                "summary": "This documentation covers the secondary management features of the Habit Tracker: setting reminders to ensure consistency and writing daily notes for reflections.",
                "techDocs": "\n\n### Purpose\nThis documentation covers the secondary management features of the Habit Tracker: setting reminders to ensure consistency and writing daily notes for reflections.\n\n### Reminders\nReminders help users stay committed by sending notifications at specific times for their chosen habits.\n\n### Files\n- **View**: `03SetHabitReminderViewUI/View/SetHabitReminderViewUI.swift`\n- **ViewModel**: `03SetHabitReminderViewUI/ViewModel/SetHabitReminderUIViewModel.swift`\n- **Popup**: `07SetReminderPopupViewUI/View/SetReminderPopupViewUI.swift`\n\n### Features\n- **Global Toggle**: Enable or disable all habit reminders at once.\n- **Specific Timing**: Set a daily time for the reminder notification.\n- **Habit Specific**: (Optional/Planned) Assign different times to different habits.\n- **Local Notifications**: When enabled, the app schedules local notifications via the iOS UserNotifications framework.\n\n### Notes\nNotes allow users to record qualitative data about their habit journey, such as why a habit was skipped or how they felt after completing one.\n\n### Files\n- **View**: `04EditHabitNotesViewUI/View/EditHabitNotesViewUI.swift`\n- **ViewModel**: Managed by the `HabitTrackingHomeDashboardUIViewModel` (via shared state).\n\n### Features\n- **Daily Reflection**: Each day has its own note field.\n- **Character Limit**: Ensures notes remain concise reflections.\n- **Edit/Write States**: Dynamically updates the UI based on whether a note already exists for the day.\n- **Persistence**: Notes are synced to the server alongside habit logs when \"Keep Moving Forward\" is tapped.\n\n### Business Logic\n- **Reminder Sync**: When a user changes reminder settings, the app calls `createRequestForSetHabitReminder` to update the backend and then schedules local notification tasks.\n- **Note Sync**: Notes are sent in the payload of the `createRequestForLoggingHabitDashboardList` API call.\n\n### Navigation\n- **Reminders**: Usually accessed from the Habit Dashboard settings or the \"Add Habits\" success flow.\n- **Notes**: Accessed directly from the Habit Dashboard by clicking \"Edit\" or \"Write\" in the notes section.",
                "code": "",
                "lang": "javascript",
                "id": "screen_reminders_notes",
                "category": "Habittrackerdocs"
            },
            {
                "title": "Screen: Streak Dashboard & Activity Details",
                "summary": "The Streak Dashboard provides users with a comprehensive overview of their consistency and progress in maintaining habits. It visualizes current streaks, longest streaks, and weekly activity to motivate users to stay on track.",
                "techDocs": "\n\n### Purpose\nThe Streak Dashboard provides users with a comprehensive overview of their consistency and progress in maintaining habits. It visualizes current streaks, longest streaks, and weekly activity to motivate users to stay on track.\n\n### Files\n- **Views**:\n    - `04StreakDashboardUI/View/StreakDashboardView.swift`\n    - `05StreakActivityDetailsUI/View/StreakActivityDetailsView.swift`\n- **ViewModels**:\n    - `04StreakDashboardUI/ViewMode/StreakDashboardViewModel.swift`\n    - `05StreakActivityDetailsUI/ViewModel/StreakActivityDetailsViewModel.swift`\n\n### UI Components\n- **Streak Overview Card**: Displays the current streak count, started date, and user rank.\n- **Milestone Progress**: Visual representation of the user's progress toward the next major streak milestone.\n- **Weekly Activity Chart**: A vertical or horizontal representation of habit completion for the current week.\n- **Longest Streak Stat**: Highlights the user's personal best record for habit consistency.\n- **Activity Feed/Details**: In-depth breakdown of habit logs for specific days, accessible via the activity details view.\n- **Info Icon**: Opens the `StreakInfoView` which explains how streaks are calculated.\n\n### Business Logic\n- **Streak Calculation**: The backend calculates streaks based on daily habit logs. A streak is maintained if at least one habit is completed each day (depending on specific business rules).\n- **Ranking**: Users are ranked against others in the community based on their streak consistency, encouraging healthy competition.\n- **Historical View**: The activity details screen allows users to scroll through past logs to see their long-term performance trends.\n\n### API Integration\n- `createRequestForFetchStreakDashboard`: Retrieves current streak stats, rankings, and weekly activity data.\n- `createRequestForFetchStreakActivityDetails`: Fetches the detailed historical log of habit completions.\n\n### Navigation\n- **Inbound**: From the Habit Dashboard by tapping the streak header or card.\n- **Outbound**:\n    - **Streak Info**: Explains the logic behind streak maintenance.\n    - **Habit Dashboard**: Returns to the main logging screen for today.",
                "code": "",
                "lang": "javascript",
                "id": "screen_streakdetails",
                "category": "Habittrackerdocs"
            }
        ]
    },
    "android": {
        "accent": "#2AD189",
        "rgb": "42, 209, 137",
        "modules": []
    },
    "web": {
        "accent": "#a855f7",
        "rgb": "168, 85, 247",
        "modules": []
    }
};